'use client';
import {useEffect,useRef,useState} from 'react';
import {Menu,ArrowRight,ArrowLeft,Map,Compass,Users,Footprints,Home,Check, X, Waves, Sunset, Fish, TreePalm, Utensils, Sailboat, ShoppingBasket, MapPin, CalendarDays, Award, Shell, HeartHandshake, Anchor, ChevronRight} from 'lucide-react';
import {Sheet,SheetContent,SheetTitle,SheetDescription,SheetClose} from '@/components/ui/sheet';
import {Sidebar,SidebarProvider,SidebarContent,SidebarMenu,SidebarMenuItem,SidebarMenuButton} from '@/components/ui/sidebar';
import {Progress} from '@/components/ui/progress';
import SanvicMap from '@/components/sanvic-map';
import {pictures,categories as defaultCategories,communities as defaultCommunities,opportunities as defaultOpportunities,type Community,type Opportunity,type Category,type DiscoverCategory} from '@/lib/sanvic-data';
import type {PublicSiteData,Place} from '@/lib/cms-types';
import {MediaGallery,PlaceCard,PlaceDetail,PlaceSheet} from '@/components/public-media';
type View='home'|'explore'|'discover'|'travelers'|'journey';
const nav=[{id:'home',label:'Home',icon:Home,sub:'The soul of San Vicente'},{id:'explore',label:'Explore',icon:Map,sub:'Ten communities, one coastline'},{id:'discover',label:'Discover',icon:Compass,sub:'Find your kind of day'},{id:'travelers',label:'Travelers',icon:Users,sub:'Find people. Share moments.'},{id:'journey',label:'Journey',icon:Footprints,sub:'Collect moments. Track your story.'}] as const;
const traits:Record<string,typeof Waves>={Surf:Waves,Mangroves:TreePalm,Sunsets:Sunset,Fishing:Fish,Nature:TreePalm,Beaches:Waves,Walking:Footprints,Food:Utensils,Market:ShoppingBasket,Boats:Sailboat,Kayak:Anchor};
function Avatars(){return <span className="avatar-stack" aria-label="Sample travelers">{[1,2,3].map(i=><img key={i} className="avatar" src={`/images/avatar-${i}.webp`} alt="" width="29" height="29"/>)}</span>}
function KnownFor({community}:{community:Community}){return <section className="known-for"><h3 className="eyebrow">Known for</h3><div>{community.known.map(t=>{const Icon=traits[t]||Compass;return <span key={t}><Icon aria-hidden="true"/><small>{t}</small></span>})}</div></section>}
function ThingsToDo({onCategory}:{onCategory:(c:Category)=>void}){const things=[{title:'Surf',img:pictures.surf,cat:'experiences'},{title:'Kayak',img:pictures.kayak,cat:'experiences'},{title:'Walk',img:pictures.beach,cat:'beaches'},{title:'Sunset',img:pictures.sunset,cat:'beaches'},{title:'Dinner',img:pictures.food,cat:'food'}] as const;return <section className="things"><h3 className="eyebrow">Things to do</h3><div className="things-grid">{things.map(t=><button key={t.title} onClick={()=>onCategory(t.cat)}><img src={t.img} alt="" loading="lazy"/><span>{t.title}</span></button>)}</div></section>}
function EditorialCard({id,title,description,image,onClick}:{id:string;title:string;description:string;image:string;onClick:()=>void}){return <button className={`editorial-card editorial-${id}`} onClick={onClick}><img src={image} alt="" loading="lazy"/><div><h2>{title}</h2><p>{description}</p></div><ArrowRight className="card-arrow" aria-hidden="true"/></button>}
function JoinButton({joined,onClick}:{joined:boolean;onClick:()=>void}){return <button className={`join-button ${joined?'joined':''}`} onClick={onClick} aria-pressed={joined}>{joined?<><Check size={13}/>Joined</>:'Join'}</button>}
function OpportunityRow({o,joined,onJoin,onOpen}:{o:Opportunity;joined:boolean;onJoin:()=>void;onOpen:()=>void}){return <article className="opportunity-row"><button className="opportunity-image" onClick={onOpen} aria-label={`View ${o.title}`}><img src={o.image} alt="" loading="lazy"/></button><div className="opportunity-info"><button onClick={onOpen}>{o.title}</button><p>{o.context}</p><span>{o.count+(joined?1:0)} travelers</span></div><JoinButton joined={joined} onClick={onJoin}/></article>}
function ContextCard({o,joined,onJoin,onOpen}:{o:Opportunity;joined:boolean;onJoin:()=>void;onOpen:()=>void}){return <article className="context-card"><button className="context-photo" onClick={onOpen} aria-label={`Explore ${o.pageTitle}`}><img src={o.image} alt="" loading="lazy"/></button><div className="context-body"><p className="eyebrow">Travelers nearby <span>Sample</span></p><h3>{o.headline}</h3><p>{o.copy}</p><div className="context-travelers"><Avatars/><span>{o.count+(joined?1:0)} travelers interested</span></div><button className={`primary-button ${joined?'is-joined':''}`} onClick={onJoin} aria-pressed={joined}>{joined?'Joined · leave plan':o.cta}{joined?<Check size={18}/>:<ArrowRight size={18}/>}</button></div></article>}
function getView(route:string):View{if(route.startsWith('community/')||route.startsWith('place/'))return'explore';if(route.startsWith('category/')||route.startsWith('opportunity/'))return'discover';return nav.some(n=>n.id===route)?route as View:'home'}
function validRoute(route:string,communities:Community[],categories:DiscoverCategory[],opportunities:Opportunity[],places:Place[]=[]){return nav.some(n=>n.id===route)||(route.startsWith('community/')&&communities.some(c=>route===`community/${c.id}`))||(route.startsWith('place/')&&places.some(p=>route===`place/${p.id}`))||(route.startsWith('category/')&&categories.some(c=>route===`category/${c.id}`))||(route.startsWith('opportunity/')&&opportunities.some(o=>route===`opportunity/${o.id}`))}
export default function SanvicApp(){
 const [route,setRoute]=useState('home');const [menu,setMenu]=useState(false);const [selected,setSelected]=useState<Community|null>(null);const [selectedPlace,setSelectedPlace]=useState<Place|null>(null);const [sheetOpen,setSheetOpen]=useState(false);const [placeSheetOpen,setPlaceSheetOpen]=useState(false);const [joined,setJoined]=useState<string[]>([]);const [visited,setVisited]=useState<string[]>([]);const [ready,setReady]=useState(false);const [notice,setNotice]=useState('');const [content,setContent]=useState<PublicSiteData|null>(null);const swipe=useRef(0);const logoClicks=useRef({count:0,last:0});
 const categories=content?.categories?.length?content.categories:defaultCategories;const communities=content?.communities?.length?content.communities:defaultCommunities;const opportunities=content?.opportunities?.length?content.opportunities:defaultOpportunities;const places=content?.places||[];const media=content?.media||[];const copy=content?.copy||{};const t=(key:string,fallback:string)=>copy[key]||fallback;
 useEffect(()=>{fetch('/api/public/site').then(r=>r.ok?r.json():null).then(d=>{if(d){setContent(d);const r=location.hash.slice(1)||'home';if(r.startsWith('place/')&&d.places?.some((p:Place)=>r===`place/${p.id}`))setRoute(r)}}).catch(()=>{});const sync=()=>{const r=location.hash.slice(1)||'home';setRoute(validRoute(r,defaultCommunities,defaultCategories,defaultOpportunities,[])?r:r.startsWith('place/')?r:'home');setSheetOpen(false);setPlaceSheetOpen(false)};sync();window.addEventListener('popstate',sync);window.addEventListener('hashchange',sync);try{const s=JSON.parse(localStorage.getItem('sanvic-journey-v1')||'{}');if(Array.isArray(s.joined))setJoined(s.joined.filter((x:string)=>defaultOpportunities.some(o=>o.id===x)));if(Array.isArray(s.visited))setVisited(s.visited.filter((x:string)=>defaultCommunities.some(c=>c.id===x)))}catch{}setReady(true);if('serviceWorker' in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});return()=>{window.removeEventListener('popstate',sync);window.removeEventListener('hashchange',sync)}},[]);
 useEffect(()=>{if(ready)try{localStorage.setItem('sanvic-journey-v1',JSON.stringify({joined,visited}))}catch{}},[joined,visited,ready]);
 useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),4000);return()=>clearTimeout(t)},[notice]);
 useEffect(()=>{if(route!=='journey')return;const heading=document.querySelector('.journey .page-heading');if(heading){const eyebrow=heading.querySelector('.eyebrow');const title=heading.querySelector('h1');const description=heading.querySelector('p:last-child');if(eyebrow)eyebrow.textContent=t('journey.eyebrow','Collect moments. Track your story.');if(title)title.textContent=t('journey.heading','Your island journey.');if(description)description.textContent=t('journey.description','A little more connected with every day.')}const cards=document.querySelectorAll('.journey .badge');content?.badges?.forEach((badge,index)=>{const card=cards[index];if(!card)return;const name=card.querySelector('h3');const description=card.querySelector('p');if(name)name.textContent=badge.name;if(description&&!card.classList.contains('earned'))description.textContent=badge.description})},[route,copy,content?.badges]);
 const navigate=(r:string)=>{setRoute(r);history.pushState(null,'',`#${r}`);setMenu(false);setSheetOpen(false);setPlaceSheetOpen(false);window.scrollTo({top:0,behavior:'instant'});};
 const logoAction=()=>{const now=Date.now();logoClicks.current=now-logoClicks.current.last<750?{count:logoClicks.current.count+1,last:now}:{count:1,last:now};if(logoClicks.current.count>=3){logoClicks.current={count:0,last:0};location.href='/admin';return}navigate('home')};
 const join=(id:string)=>{const has=joined.includes(id);setJoined(p=>has?p.filter(x=>x!==id):[...p,id]);setNotice(has?'Removed from your sample plans.':'Added to your sample plans. View it in Journey.');};
 const visit=(id:string)=>{setVisited(p=>p.includes(id)?p.filter(x=>x!==id):[...p,id]);setNotice(visited.includes(id)?'Visit removed from your journey.':'A new community in your story.');};
 const view=getView(route);const community=communities.find(c=>route===`community/${c.id}`);const category=categories.find(c=>route===`category/${c.id}`);const opportunity=opportunities.find(o=>route===`opportunity/${o.id}`);const place=places.find(p=>route===`place/${p.id}`);const isDetail=!!community||!!category||!!opportunity||!!place;const categoryPlaces=category?places.filter(place=>({experiences:['Tour','Sightseeing','Activity'],food:['Cafe','Restaurant'],beaches:['Beach','Island'],stay:['Accommodation'],events:[],services:['Transport','Service']}[category.id] as string[]).includes(place.type)):[];
 const selectCommunity=(c:Community)=>{setSelectedPlace(null);setPlaceSheetOpen(false);setSelected(c);setSheetOpen(true)};
 const selectPlace=(p:Place)=>{setSelected(null);setSheetOpen(false);setSelectedPlace(p);setPlaceSheetOpen(true)};
 const back=()=>{if(community||place)navigate('explore');else if(opportunity)navigate(`category/${opportunity.category}`);else navigate('discover')};
 return <div className={`app-shell app-${view} ${isDetail?'app-detail':''}`}><a href="#main-content" className="skip-link" onClick={e=>{e.preventDefault();document.getElementById('main-content')?.focus()}}>Skip to content</a><header className="site-header"><button className="wordmark" onClick={logoAction} aria-label="SANVIC home"><img src="/sanvic-logo.png" alt="" width="515" height="65"/><small>SAN VICENTE, PALAWAN</small></button><div className="header-actions"><nav className="desktop-nav" aria-label="Main navigation">{nav.map(n=><button className={view===n.id?'active':''} key={n.id} onClick={()=>navigate(n.id)} aria-current={view===n.id?'page':undefined}>{n.label}</button>)}</nav><button className="icon-button" aria-label="Open menu" aria-expanded={menu} onClick={()=>setMenu(true)}><Menu/></button></div></header>
 <main id="main-content" tabIndex={-1} key={route}>
 {place&&<PlaceDetail place={place} media={media} onBack={back} onCommunity={()=>{const match=communities.find(c=>c.name===place.barangay);navigate(match?`community/${match.id}`:'explore')}}/>}
 {route==='home'&&<section className="home view-enter"><img className="home-bg" src={pictures.hero} alt="Golden light over the forested coastline of Port Barton, San Vicente" fetchPriority="high"/><div><p className="eyebrow home-eyebrow">{t('home.eyebrow','The soul of San Vicente')}</p><h1>{t('home.heading','Slow down.\nTune in.\nYou’re in\nSan Vicente.').split('\n').map((line,index)=><span className={index>1?'gold-line':''} key={`${line}-${index}`}>{line}<br/></span>)}</h1><div className="home-copy">{t('home.body','Some places ask you to do more.\nSan Vicente asks you to do less.\nWake slowly. Swim longer.\nEat what arrived this morning.\nLearn the names of fishermen.\nStay long enough to discover your own favorite beach.\nAnd perhaps leave carrying fewer plans than when you arrived.')}</div><p className="home-endnote">{t('home.endnote','10 communities. Hundreds of stories.\nOne coastline waiting to be explored.')}</p><div className="home-bottom"><button className="nearby-pill" onClick={()=>navigate('travelers')}><Avatars/><span>{t('home.travelers','41 Travelers Nearby')} <small>Sample community</small></span></button><button className="text-link" onClick={()=>navigate('explore')}>Explore San Vicente<ArrowRight/></button></div></div><span className="home-coordinate">10.5250° N &nbsp; 119.2750° E · PALAWAN</span></section>}
 {route==='explore'&&<SanvicMap active={selected} activePlace={selectedPlace} onSelect={selectCommunity} communities={communities} places={places} copy={copy} onPlaceSelect={selectPlace}/>} {/* published locations are mapped by the CMS */}
 {route==='discover'&&<section className="page discover view-enter"><div className="page-heading"><p className="eyebrow">{t('discover.eyebrow','A little curiosity goes a long way')}</p><h1>{t('discover.heading','Follow what moves you.')}</h1><p>{t('discover.description','No checklist. Just possibilities.')}</p></div><div className="editorial-grid">{categories.map(c=><EditorialCard key={c.id} {...c} onClick={()=>navigate(`category/${c.id}`)}/>)}</div></section>}
 {route==='travelers'&&<section className="page travelers view-enter"><div className="travelers-layout"><div className="travelers-editorial"><img src={pictures.sunset} alt="People gathering on the beach at sunset in Port Barton"/><div><p className="eyebrow">Find people. Share moments.</p><h2>Some days are<br/>better together.</h2><Avatars/></div></div><div className="travelers-list"><div className="page-heading"><p className="eyebrow">{t('travelers.eyebrow','Around San Vicente')}</p><h1>{t('travelers.heading','Travelers Nearby')}</h1><p>{t('travelers.description','A shared boat. A spare seat. A new friend.')}</p></div><p className="sample-note"><span>Preview community</span> Sample plans and traveler counts.</p><div>{opportunities.map(o=><OpportunityRow key={o.id} o={o} joined={joined.includes(o.id)} onJoin={()=>join(o.id)} onOpen={()=>navigate(`opportunity/${o.id}`)}/>)}</div><p className="quiet-note">Joining saves a sample plan on this device. It doesn’t contact other travelers or reserve a place.</p></div></div></section>}
 {community&&<section className="community-page view-enter"><div className="community-hero"><img src={community.image} alt="San Vicente coastline"/><button className="icon-button back-button" onClick={back} aria-label="Back to Municipality Explorer"><ArrowLeft/></button><span className="eyebrow">San Vicente · Community {String(communities.indexOf(community)+1).padStart(2,'0')}</span></div><div className="community-content"><div className="community-story"><p className="eyebrow">A place to slow down</p><h1>{community.name}</h1><p className="community-description">{community.description}</p><div className="community-social"><Avatars/><span>{community.count} travelers nearby <small>Sample community</small></span></div><button className={`visit-button ${visited.includes(community.id)?'visited':''}`} onClick={()=>visit(community.id)} aria-pressed={visited.includes(community.id)}>{visited.includes(community.id)?<Check size={17}/>:<MapPin size={17}/>} {visited.includes(community.id)?'Visited · in your journey':'Mark as visited'}</button><KnownFor community={community}/><ThingsToDo onCategory={c=>navigate(`category/${c}`)}/>{places.filter(place=>place.barangay===community.name).length>0&&<section className="community-places"><p className="eyebrow">Places in {community.name}</p>{places.filter(place=>place.barangay===community.name).map(place=><PlaceCard key={place.id} place={place} media={media} onOpen={()=>navigate(`place/${place.id}`)}/>)}</section>}</div><div className="community-aside"><p className="eyebrow">A moment to share</p>{opportunities.length>0&&<ContextCard o={opportunities[Math.min(community.id==='alimanguan'?4:community.id==='poblacion'?3:community.id==='port-barton'?0:1,opportunities.length-1)]} joined={joined.includes(opportunities[Math.min(community.id==='alimanguan'?4:community.id==='poblacion'?3:community.id==='port-barton'?0:1,opportunities.length-1)].id)} onJoin={()=>join(opportunities[Math.min(community.id==='alimanguan'?4:community.id==='poblacion'?3:community.id==='port-barton'?0:1,opportunities.length-1)].id)} onOpen={()=>navigate(`opportunity/${opportunities[Math.min(community.id==='alimanguan'?4:community.id==='poblacion'?3:community.id==='port-barton'?0:1,opportunities.length-1)].id}`)}/>}</div></div></section>}
 {category&&<section className="detail-page view-enter"><div className="detail-hero"><img src={category.image} alt={`${category.title} in an island setting`}/><button className="icon-button back-button" onClick={back} aria-label="Back to Discover"><ArrowLeft/></button><div className="detail-title"><p className="eyebrow">Discover San Vicente</p><h1>{category.title}</h1><p>{category.description}</p></div></div><div className="detail-story"><p className="eyebrow">Make a little room for this</p><h2>{category.story}</h2><div className="context-list">{opportunities.filter(o=>o.category===category.id).map(o=><ContextCard key={o.id} o={o} joined={joined.includes(o.id)} onJoin={()=>join(o.id)} onOpen={()=>navigate(`opportunity/${o.id}`)}/>)}</div>{categoryPlaces.length>0&&<section className="place-list"><p className="eyebrow">Local directory</p><h2>Places worth knowing.</h2>{categoryPlaces.map(place=><PlaceCard key={place.id} place={place} media={media} onOpen={()=>navigate(`place/${place.id}`)}/>)}</section>}{category.id==='stay'&&<div className="stay-communities">{['port-barton','alimanguan','poblacion'].map(id=>communities.find(x=>x.id===id)).filter(Boolean).map(c=><button key={c!.id} onClick={()=>navigate(`community/${c!.id}`)}><MapPin/><span><strong>{c!.name}</strong><small>Explore the community</small></span><ArrowRight/></button>)}</div>}<p className="quiet-note">Activity photography is representative. Community plans are samples.</p></div></section>}
 {opportunity&&<section className="detail-page opportunity-page view-enter"><div className="detail-hero"><img src={opportunity.image} alt={opportunity.pageTitle}/><button className="icon-button back-button" onClick={back} aria-label="Back to category"><ArrowLeft/></button><div className="detail-title"><p className="eyebrow">{opportunity.where}</p><h1>{opportunity.pageTitle}</h1><p>{opportunity.context.split(' · ')[1]}</p></div></div><div className="detail-story"><p className="eyebrow">Find people. Share moments.</p><h2>{opportunity.headline}</h2><div className="opportunity-meta"><span><MapPin size={17}/>{opportunity.where}</span><span><CalendarDays size={17}/>{opportunity.when}</span></div><ContextCard o={opportunity} joined={joined.includes(opportunity.id)} onJoin={()=>join(opportunity.id)} onOpen={()=>{}}/><p className="quiet-note">This is a sample gathering. Joining records your interest on this device only; no booking or message is sent.</p></div></section>}
 {route==='journey'&&<section className="page journey view-enter"><div className="page-heading"><p className="eyebrow">Collect moments. Track your story.</p><h1>Your island journey.</h1><p>A little more connected with every day.</p></div><div className="journey-summary"><div className="journey-profile"><img src="/images/avatar-1.webp" alt="Explorer profile"/><div><p className="gold">Level {1+Math.floor((joined.length+visited.length)/2)}</p><h2>Explorer</h2><span>Your journey on this device</span></div></div><div className="journey-stat"><div><span>Communities visited</span><strong>{visited.length} <small>/ 10</small></strong></div><Progress value={visited.length*10} aria-label="Communities visited"/></div><div className="journey-stat"><div><span>Sample experiences joined</span><strong>{joined.length} <small>/ 6</small></strong></div><Progress value={joined.length/6*100} aria-label="Sample experiences joined"/></div></div><section className="badge-section"><p className="eyebrow">Your collection</p><h2>Stories you can keep.</h2><div className="badge-grid">{[{name:'First Connection',icon:HeartHandshake,earned:joined.length>0,desc:'Join your first sample plan'},{name:'Island Hopper',icon:Sailboat,earned:joined.includes('island-hopping'),desc:'Join an island-hopping plan'},{name:'Sunset Chaser',icon:Sunset,earned:joined.includes('sunset'),desc:'Join a sunset plan'},{name:'Barangay Collector',icon:MapPin,earned:visited.length>0,desc:'Mark your first community visited'},{name:'Pathfinder',icon:Footprints,earned:visited.length>=5,desc:'Visit five communities'},{name:'SanVic Ambassador',icon:Award,earned:visited.length===10,desc:'Visit all ten communities'}].map(b=><article key={b.name} className={`badge ${b.earned?'earned':''}`}><span className="badge-icon"><b.icon/>{b.earned&&<Check className="badge-check"/>}</span><h3>{b.name}</h3><p>{b.earned?'Collected':b.desc}</p></article>)}</div></section><div className="journey-bottom"><section><h2>Along the coast</h2><div className="visited-list">{communities.map(c=><button key={c.id} onClick={()=>navigate(`community/${c.id}`)}><span className={visited.includes(c.id)?'visited-indicator checked':'visited-indicator'}>{visited.includes(c.id)?<Check size={12}/>:null}</span><span>{c.name}</span><ChevronRight size={16}/></button>)}</div></section><section><h2>Your shared moments</h2>{joined.length?opportunities.filter(o=>joined.includes(o.id)).map(o=><OpportunityRow key={o.id} o={o} joined onJoin={()=>join(o.id)} onOpen={()=>navigate(`opportunity/${o.id}`)}/>):<div className="journey-empty"><Shell/><p>Your next story hasn’t happened yet.</p><button className="text-link" onClick={()=>navigate('travelers')}>Find a moment to share<ArrowRight/></button></div>}<p className="quiet-note">Plans are samples. Visits and progress stay on this device.</p></section></div></section>}
 {community&&<MediaGallery ids={community.mediaIds} media={media} title={`Life in ${community.name}`}/>} {/* community media */}
 {category&&<MediaGallery ids={category.mediaIds} media={media} title={`More ${category.title.toLowerCase()}`}/>} {/* discover media */}
 {opportunity&&<MediaGallery ids={opportunity.mediaIds} media={media} title={opportunity.pageTitle}/>} {/* traveler media */}
 {route==='journey'&&<MediaGallery ids={content?.badges?.flatMap(b=>b.mediaIds||[])} media={media} title="Moments from the journey"/>}
 </main>
 <nav className="bottom-nav" aria-label="Mobile navigation">{nav.map(n=><button className={view===n.id?'active':''} key={n.id} onClick={()=>navigate(n.id)} aria-current={view===n.id?'page':undefined}><n.icon/><span>{n.label}</span></button>)}</nav>
 <Sheet open={menu} onOpenChange={setMenu}><SheetContent className="menu-sheet" side="right" showCloseButton={false}><SheetTitle className="sr-only">Explore SANVIC</SheetTitle><SheetDescription className="sr-only">Navigate San Vicente’s communities, experiences, and your journey.</SheetDescription><div className="menu-top"><img className="menu-logo" src="/sanvic-logo.png" alt="SANVIC" width="515" height="65"/><SheetClose asChild><button className="icon-button" aria-label="Close menu"><X/></button></SheetClose></div><SidebarProvider className="menu-provider" defaultOpen={true}><Sidebar collapsible="none" className="menu-sidebar"><SidebarContent><SidebarMenu>{nav.map((n,i)=><SidebarMenuItem key={n.id}><SidebarMenuButton asChild isActive={view===n.id}><button onClick={()=>navigate(n.id)}><span className="menu-index">0{i+1}</span><span><strong>{n.label}</strong><small>{n.sub}</small></span><ArrowRight/></button></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarContent></Sidebar></SidebarProvider><div className="menu-footer"><p>Slow down. Tune in.</p><span>SAN VICENTE, PALAWAN · 2027</span><a href="/photo-credits.json" target="_blank" rel="noreferrer">Photography credits</a></div></SheetContent></Sheet>
 <Sheet open={sheetOpen} onOpenChange={setSheetOpen}><SheetContent side="bottom" className="community-sheet" showCloseButton={false}>{selected&&<><div className="sheet-handle" onTouchStart={e=>swipe.current=e.touches[0].clientY} onTouchEnd={e=>{if(e.changedTouches[0].clientY-swipe.current>60)setSheetOpen(false)}}><span/></div><SheetClose asChild><button className="sheet-close icon-button" aria-label="Close community"><X/></button></SheetClose><div className="sheet-inner"><SheetTitle className="community-sheet-title">{selected.name}</SheetTitle><SheetDescription className="sheet-description">{selected.description}</SheetDescription><div className="community-social"><Avatars/><span>{selected.count} travelers nearby <small>Sample community</small></span></div><KnownFor community={selected}/><ThingsToDo onCategory={c=>navigate(`category/${c}`)}/><button className="primary-button" onClick={()=>navigate(`community/${selected.id}`)}>Explore Community<ArrowRight size={19}/></button></div></>}</SheetContent></Sheet>
 <Sheet open={placeSheetOpen} onOpenChange={setPlaceSheetOpen}><SheetContent side="bottom" className="community-sheet place-map-sheet" showCloseButton={false}>{selectedPlace&&<><div className="sheet-handle"><span/></div><SheetClose asChild><button className="sheet-close icon-button" aria-label="Close location"><X/></button></SheetClose><SheetTitle className="sr-only">{selectedPlace.name}</SheetTitle><SheetDescription className="sr-only">{selectedPlace.description}</SheetDescription><PlaceSheet place={selectedPlace} media={media} onOpen={()=>navigate(`place/${selectedPlace.id}`)}/></>}</SheetContent></Sheet>
 <div className={`app-notice ${notice?'visible':''}`} role="status" aria-live="polite">{notice}</div>
 </div>
}
