"use client";

import { FormEvent, useRef, useState } from "react";
import { Camera, LoaderCircle, Trash2, Upload } from "lucide-react";
import { createClient } from "@supabase/supabase-js";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import type { TravelerUpload } from "@/lib/cms-types";

export function NicknameDialog({ open, busy, onOpenChange, onSubmit }: { open:boolean; busy:boolean; onOpenChange:(open:boolean)=>void; onSubmit:(nickname:string)=>void }) {
  const [nickname,setNickname]=useState("");
  const submit=(event:FormEvent)=>{event.preventDefault();if(nickname.trim())onSubmit(nickname.trim())};
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="traveler-dialog"><DialogHeader><p className="eyebrow">Your SANVIC journey</p><DialogTitle>What should we call you?</DialogTitle><DialogDescription>Choose a nickname. It stays with this browser for one year and appears only when you join a public plan or share an approved photo.</DialogDescription></DialogHeader><form onSubmit={submit}><label><span>Nickname</span><input autoFocus maxLength={24} value={nickname} onChange={event=>setNickname(event.target.value)} placeholder="Coast Wanderer"/></label><button className="primary-button" disabled={busy||!nickname.trim()}>{busy?<LoaderCircle className="spin"/>:"Continue"}</button></form></DialogContent></Dialog>;
}

export function ExperienceUploader({ opportunityId, uploads, hasTraveler, ensureTraveler, onChanged, notify }: { opportunityId:string; uploads:TravelerUpload[]; hasTraveler:boolean; ensureTraveler:(next:()=>void)=>void; onChanged:()=>Promise<void>|void; notify:(message:string)=>void }) {
  const input=useRef<HTMLInputElement>(null); const [busy,setBusy]=useState(false); const [caption,setCaption]=useState("");
  const start=()=>ensureTraveler(()=>input.current?.click());
  const upload=async(files:FileList|null)=>{if(!files?.length)return;setBusy(true);try{const key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;if(!key)throw new Error("Photo uploads are being configured.");const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,key);for(const file of Array.from(files)){const ticketResponse=await fetch("/api/travelers/uploads",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({opportunityId,filename:file.name,contentType:file.type,sizeBytes:file.size})});const ticket=await ticketResponse.json();if(!ticketResponse.ok)throw new Error(ticket.error||"Unable to prepare upload.");const {error}=await supabase.storage.from("traveler-experiences").uploadToSignedUrl(ticket.path,ticket.token,file,{contentType:file.type});if(error)throw error;const finish=await fetch("/api/travelers/uploads",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:ticket.id,caption})});const body=await finish.json();if(!finish.ok)throw new Error(body.error||"Unable to finish upload.");}notify("Photo sent for admin review. It will appear after approval.");setCaption("");await onChanged()}catch(error){notify(error instanceof Error?error.message:"Unable to upload photo.")}finally{setBusy(false);if(input.current)input.current.value=""}};
  const remove=async(id:string)=>{if(!confirm("Remove this photo from your journey?"))return;const response=await fetch("/api/travelers/uploads",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id})});const body=await response.json();if(!response.ok){notify(body.error||"Unable to remove photo.");return}await onChanged()};
  return <section className="experience-uploader"><div><p className="eyebrow">Share your experience</p><h3>Your view of this moment.</h3><p>Add several photos from your device. SANVIC reviews each image before it appears publicly.</p></div><label><span>Optional caption for these photos</span><input value={caption} maxLength={500} onChange={event=>setCaption(event.target.value)} placeholder="What made this moment special?"/></label><input ref={input} hidden type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={event=>upload(event.target.files)}/><button className="primary-button" onClick={start} disabled={busy}>{busy?<LoaderCircle className="spin"/>:<Upload/>}{busy?"Uploading…":hasTraveler?"Add photos":"Choose a nickname & add photos"}</button>{uploads.length>0&&<div className="my-experience-grid">{uploads.map(item=><article key={item.id}><img src={item.url} alt={item.caption||item.filename||"Your experience"}/><span>{item.status}</span><button onClick={()=>remove(item.id)} aria-label="Remove photo"><Trash2/></button></article>)}</div>}</section>;
}

export function TravelerExperienceGallery({ uploads }: { uploads:TravelerUpload[] }) { if(!uploads.length)return null;return <section className="traveler-experience-gallery"><p className="eyebrow">Shared by travelers</p><h2>Moments from this experience.</h2><div>{uploads.map(item=><figure key={item.id}><img src={item.url} alt={item.caption||`Shared by ${item.nickname||"a traveler"}`} loading="lazy"/><figcaption><Camera/>{item.caption||"A SANVIC moment"}<small>{item.nickname}</small></figcaption></figure>)}</div></section> }
