import { categories, communities, opportunities } from "./sanvic-data";

export const copySeed = [
  ["theme.background", "Theme", "Main and loading background", "#020e26"],
  ["theme.surface", "Theme", "Cards and panels background", "#07182f"],
  ["theme.action", "Theme", "Buttons and controls background", "#123a5c"],
  ["loading.tagline", "Loading Screen", "Tagline", "The San Vicente Travel Hub"],
  ["loading.subline", "Loading Screen", "Supporting line", "Curated by the people who live here"],
  ["loading.footer", "Loading Screen", "Footer label", "PALAWAN"],
  ["home.eyebrow", "Home", "Eyebrow", "The soul of San Vicente"],
  ["home.heading", "Home", "Hero heading", "Slow down.\nTune in.\nYou’re in\nSan Vicente."],
  ["home.body", "Home", "Editorial introduction", "Some places ask you to do more.\nSan Vicente asks you to do less.\nWake slowly. Swim longer.\nEat what arrived this morning.\nLearn the names of fishermen.\nStay long enough to discover your own favorite beach.\nAnd perhaps leave carrying fewer plans than when you arrived."],
  ["home.endnote", "Home", "End note", "10 communities. Hundreds of stories.\nOne coastline waiting to be explored."],
  ["home.travelers", "Home", "Nearby traveler label", "41 Travelers Nearby"],
  ["explore.eyebrow", "Explore", "Eyebrow", "Municipality Explorer"],
  ["explore.heading", "Explore", "Heading", "A coast.\nTen communities."],
  ["explore.description", "Explore", "Description", "Find your corner of San Vicente."],
  ["discover.eyebrow", "Discover", "Eyebrow", "A little curiosity goes a long way"],
  ["discover.heading", "Discover", "Heading", "Follow what moves you."],
  ["discover.description", "Discover", "Description", "No checklist. Just possibilities."],
  ["travelers.eyebrow", "Travelers", "Eyebrow", "Around San Vicente"],
  ["travelers.heading", "Travelers", "Heading", "Travelers Nearby"],
  ["travelers.description", "Travelers", "Description", "A shared boat. A spare seat. A new friend."],
  ["travelers.liveNote", "Travelers", "Live community note", "Choose a plan. We’ll take you to the place."],
  ["travelers.joinNotice", "Travelers", "Joined confirmation", "Added to your Journey."],
  ["journey.eyebrow", "Journey", "Eyebrow", "Collect moments. Track your story."],
  ["journey.heading", "Journey", "Heading", "Your island journey."],
  ["journey.description", "Journey", "Description", "A little more connected with every day."],
  ["journey.empty", "Journey", "Empty Journey message", "Your San Vicente story starts here."],
  ["journey.findCta", "Journey", "Find a plan button", "Find something that feels right"],
  ["onboarding.eyebrow", "Onboarding", "Eyebrow", "Welcome to San Vicente"],
  ["onboarding.identity.heading", "Onboarding", "First question", "Are you visiting or do you live here?"],
  ["onboarding.identity.body", "Onboarding", "First question note", "We’ll shape SANVIC around the way you know the coast."],
  ["onboarding.mood.heading", "Onboarding", "Second question", "What feels right today?"],
  ["onboarding.mood.body", "Onboarding", "Second question note", "Choose one or more. There is no wrong kind of day."],
  ["onboarding.interest.heading", "Onboarding", "Third question", "Where should we begin?"],
  ["onboarding.interest.body", "Onboarding", "Third question note", "Pick a starting point and we’ll take you there."],
  ["onboarding.next", "Onboarding", "Continue button", "Continue"],
  ["onboarding.finish", "Onboarding", "Finish button", "Show me San Vicente"],
  ["onboarding.back", "Onboarding", "Back button", "Back"],
  ["onboarding.skip", "Onboarding", "Skip button", "Skip for now"],
] as const;

export const itemSeed = [
  ...communities.map((item, index) => ({ id: `community-${item.id}`, kind: "community", slug: item.id, title: item.name, data: item, sortOrder: index })),
  ...categories.map((item, index) => ({ id: `category-${item.id}`, kind: "category", slug: item.id, title: item.title, data: item, sortOrder: index })),
  ...opportunities.map((item, index) => ({ id: `opportunity-${item.id}`, kind: "opportunity", slug: item.id, title: item.title, data: item, sortOrder: index })),
  ...[
    {id:"visitor",title:"I’m visiting",description:"Beaches, stays, tours and the essentials.",stage:"identity",audience:"all",route:"discover",image:"/images/hero.webp"},
    {id:"local",title:"I live here",description:"Local events, new places and nearby moments.",stage:"identity",audience:"all",route:"discover",image:"/images/beach.webp"},
    {id:"island-hopping",title:"Island hopping",description:"A day on the water.",stage:"mood",audience:"all",route:"category/experiences",image:"/images/kayak.webp"},
    {id:"hammock",title:"Beach and hammock",description:"Nothing urgent. Just the coast.",stage:"mood",audience:"all",route:"category/beaches",image:"/images/stay.webp"},
    {id:"eat",title:"Eat somewhere special",description:"Fresh catches and tables worth finding.",stage:"mood",audience:"all",route:"category/food",image:"/images/food.webp"},
    {id:"local-spots",title:"Explore local spots",description:"Find the places people return to.",stage:"mood",audience:"all",route:"explore",image:"/images/beach.webp"},
    {id:"active",title:"Surf or get active",description:"Move with the water and the morning.",stage:"mood",audience:"all",route:"category/experiences",image:"/images/surf.webp"},
    {id:"tonight",title:"See what’s happening tonight",description:"Music, gatherings and shared tables.",stage:"mood",audience:"all",route:"category/events",image:"/images/events.webp"},
    {id:"restaurants",title:"Best restaurants nearby",description:"Start with food close to you.",stage:"interest",audience:"all",route:"category/food",image:"/images/food.webp"},
    {id:"long-beach",title:"Local spots along Long Beach",description:"Follow the coast at your own pace.",stage:"interest",audience:"all",route:"explore",image:"/images/sunset.webp"},
    {id:"islands",title:"Islands and boat tours",description:"Find your way onto the water.",stage:"interest",audience:"visitor",route:"category/experiences",image:"/images/kayak.webp"},
    {id:"quiet-beaches",title:"Quiet beaches",description:"A softer stretch of sand.",stage:"interest",audience:"all",route:"category/beaches",image:"/images/beach.webp"},
    {id:"cafes",title:"Cafés and sunset drinks",description:"Stay for the changing light.",stage:"interest",audience:"all",route:"category/food",image:"/images/sunset.webp"},
    {id:"events",title:"Events happening today",description:"See what the coast is sharing.",stage:"interest",audience:"local",route:"category/events",image:"/images/events.webp"},
    {id:"surprise",title:"Surprise me",description:"Let curiosity choose the first stop.",stage:"interest",audience:"all",route:"discover",image:"/images/hero.webp"},
  ].map((item,index)=>({id:`onboarding-${item.id}`,kind:"onboarding",slug:item.id,title:item.title,data:item,sortOrder:index})),
  ...[
    { id: "first-connection", name: "First Connection", description: "Join your first plan", rule: "joined", threshold: 1 },
    { id: "island-hopper", name: "Island Hopper", description: "Join an island-hopping plan", rule: "opportunity", threshold: 1, targetId: "island-hopping" },
    { id: "sunset-chaser", name: "Sunset Chaser", description: "Join a sunset plan", rule: "opportunity", threshold: 1, targetId: "sunset" },
    { id: "barangay-collector", name: "Barangay Collector", description: "Visit your first community", rule: "visited", threshold: 1 },
    { id: "pathfinder", name: "Pathfinder", description: "Visit five communities", rule: "visited", threshold: 5 },
    { id: "sanvic-ambassador", name: "SanVic Ambassador", description: "Visit all ten communities", rule: "visited", threshold: 10 },
  ].map((item, index) => ({ id: `badge-${item.id}`, kind: "badge", slug: item.id, title: item.name, data: item, sortOrder: index })),
];

export const baiaSeed = {
  id: "place-baia",
  name: "BAIA",
  type: "Accommodation",
  barangay: "Poblacion",
  googleMapsUrl: "https://maps.google.com/?cid=10200203730032398615",
  googlePlaceId: "",
  sourceLatitude: 10.5311,
  sourceLongitude: 119.3412,
  displayLatitude: 10.5311,
  displayLongitude: 119.3412,
  address: "Poblacion, San Vicente, Palawan",
  phone: "",
  website: "",
  description: "A place to stay in Poblacion, San Vicente.",
  bookingUrl: "",
  coverMediaId: "",
  photoIds: [] as string[],
  rooms: [
    {
      id: "room-baia-double-patio",
      name: "Double Room with Patio",
      units: 3,
      size: "20 m²",
      beds: "1 queen bed",
      description: "The double room offers air conditioning, a tea and coffee maker, a terrace with sea views as well as a private bathroom featuring a walk-in shower. The unit offers 1 bed.",
      chips: ["20 m²", "Balcony", "Sea view", "Garden view", "Air conditioning", "Patio", "Private bathroom", "Terrace", "Coffee machine", "Free Wifi"],
      groups: [
        { title: "In your private bathroom", items: ["Free toiletries", "Towels", "Toilet", "Hairdryer", "Bath or shower", "Toilet paper"] },
        { title: "View", items: ["Sea view", "Garden view"] },
        { title: "Facilities", items: ["Balcony", "Terrace", "Air conditioning", "Streaming service (like Netflix)", "Hardwood or parquet floors", "Linen", "Socket near the bed", "Cleaning products", "Desk", "Seating area", "Video", "Coffee machine", "Tea/Coffee maker", "Heating", "Fan", "Electric kettle", "Outdoor furniture", "Outdoor dining area", "Patio", "Wake-up service", "Wardrobe or closet", "Dining area", "Dining table", "Entire unit located on ground floor", "Clothes rack", "Board games/puzzles", "Carbon monoxide detector"] },
        { title: "Smoking", items: ["No smoking"] },
      ],
      photoIds: [] as string[],
    },
  ],
  status: "published",
  featured: true,
  verified: true,
  sortOrder: 0,
};
