export const pictures={hero:'/images/hero.webp',beach:'/images/beach.webp',kayak:'/images/kayak.webp',food:'/images/food.webp',sunset:'/images/sunset.webp',stay:'/images/stay.webp',events:'/images/events.webp',surf:'/images/surf.webp',transport:'/images/transport.webp'};
export type Category='experiences'|'food'|'beaches'|'stay'|'events'|'services';
export type DiscoverCategory={id:Category;title:string;description:string;image:string;story:string;mediaIds?:string[]};
export const categories:DiscoverCategory[]=[
{id:'experiences',title:'Experiences',description:'Adventure that stays with you.',image:pictures.kayak,story:'Paddle out. Take the long way. Leave a little room for the unexpected.'},
{id:'food',title:'Food',description:'Local flavors. Fresh catches.',image:pictures.food,story:'Follow the day’s catch, find a seat at the table, and stay for one more story.'},
{id:'beaches',title:'Beaches',description:'Find your perfect stretch of sand.',image:pictures.beach,story:'Bare feet, salt air, and an afternoon with nowhere else to be.'},
{id:'stay',title:'Stay',description:'Sleep where mornings arrive slowly.',image:pictures.stay,story:'A little closer to the sea. A little further from your usual routine.'},
{id:'events',title:'Events',description:'See what’s happening around you.',image:pictures.events,story:'An evening worth stepping out for. Good music, familiar faces, new friends.'},
{id:'services',title:'Services',description:'Everything you need, nothing you don’t.',image:pictures.transport,story:'Find your way along the coast, with a little help from the people around you.'},
];
export type Community={id:string;name:string;boundary:string;lon:number;lat:number;description:string;known:string[];image:string;count:number;mediaIds?:string[]};
export const communities:Community[]=[
{id:'binga',name:'Binga',boundary:'Binga',lon:119.312,lat:10.769,description:'Open coastline. Quiet villages. Long afternoons at the northern edge of San Vicente.',known:['Beaches','Fishing','Sunsets','Walking','Nature'],image:pictures.beach,count:3},
{id:'new-canipo',name:'New Canipo',boundary:'New Canipo',lon:119.325,lat:10.698,description:'Coastal roads, green hills, and a gentler rhythm. Take your time getting here.',known:['Nature','Beaches','Fishing','Walking','Sunsets'],image:pictures.hero,count:2},
{id:'sto-nino',name:'Sto. Niño',boundary:'Santo Niño',lon:119.331,lat:10.649,description:'Fishing boats on the shore. Unhurried mornings. Everyday life beside the sea.',known:['Fishing','Beaches','Sunsets','Nature','Walking'],image:pictures.beach,count:4},
{id:'alimanguan',name:'Alimanguan',boundary:'Alimanguan',lon:119.325,lat:10.606,description:'Quiet surf mornings. A fishing village beside a long, open beach. Stay for the sunset.',known:['Surf','Mangroves','Sunsets','Fishing','Nature'],image:pictures.beach,count:18},
{id:'san-isidro',name:'San Isidro',boundary:'San Isidro',lon:119.3037,lat:10.5658,description:'Long Beach at your doorstep. Walk until you find a stretch of sand to call your own.',known:['Beaches','Sunsets','Walking','Fishing','Nature'],image:pictures.hero,count:6},
{id:'new-agutaya',name:'New Agutaya',boundary:'New Agutaya',lon:119.284,lat:10.543,description:'Beach mornings and village afternoons. Follow the coastline, then follow your curiosity.',known:['Beaches','Food','Sunsets','Walking','Nature'],image:pictures.beach,count:7},
{id:'poblacion',name:'Poblacion',boundary:'Poblacion',lon:119.272,lat:10.524,description:'The everyday heart of San Vicente. Market visits, seaside walks, and a place to begin.',known:['Food','Market','Boats','Sunsets','Walking'],image:pictures.sunset,count:11},
{id:'kemdeng',name:'Kemdeng',boundary:'Kemdeng',lon:119.264,lat:10.486,description:'Green hills meet a quiet bay. Take the slower road and let the day unfold.',known:['Beaches','Nature','Walking','Fishing','Sunsets'],image:pictures.beach,count:5},
{id:'port-barton',name:'Port Barton',boundary:'Port Barton',lon:119.179,lat:10.411,description:'Island-hopping days. Barefoot evenings. A small beach town with plenty of stories.',known:['Boats','Kayak','Food','Beaches','Sunsets'],image:pictures.hero,count:23},
{id:'caruray',name:'Caruray',boundary:'Caruray',lon:119.033,lat:10.32,description:'The quieter southern coast. Fishing communities, sheltered water, and room to wander.',known:['Fishing','Nature','Beaches','Boats','Sunsets'],image:pictures.beach,count:3},
];
export type Opportunity={id:string;title:string;context:string;count:number;image:string;category:Category;pageTitle:string;headline:string;copy:string;cta:string;where:string;when:string;mediaIds?:string[];joinedNicknames?:string[]};
export const opportunities:Opportunity[]=[
{id:'island-hopping',title:'Island hopping tomorrow',context:'Port Barton · A day on the water',count:12,image:pictures.kayak,category:'experiences',pageTitle:'Island hopping',headline:'Going island hopping tomorrow?',copy:'12 travelers are planning a trip. Share boats, split costs, make friends.',cta:'Find Travelers',where:'Port Barton',when:'Tomorrow · 8:30 AM'},
{id:'sunset',title:'Long Beach sunset',context:'Long Beach · The golden hour',count:4,image:pictures.sunset,category:'beaches',pageTitle:'Long Beach',headline:'Sunset plans?',copy:'4 travelers are meeting at Long Beach. Bring yourself. Stay until the sky changes.',cta:'Join a Sunset Meetup',where:'Long Beach',when:'Tomorrow · 5:00 PM'},
{id:'live-music',title:'Live music tonight',context:'Port Barton · An easy evening',count:17,image:pictures.events,category:'events',pageTitle:'Live music',headline:'A good night starts here.',copy:'17 travelers are interested in this evening. Find someone to go with.',cta:'See Who’s Going',where:'Port Barton',when:'Tonight · 7:30 PM'},
{id:'dinner',title:'Dinner companions',context:'Poblacion · Room at the table',count:5,image:pictures.food,category:'food',pageTitle:'A table by the coast',headline:'Dinner is better together.',copy:'5 travelers are looking for dinner companions tonight. Pull up a chair.',cta:'Meet Travelers',where:'Poblacion',when:'Tonight · 6:30 PM'},
{id:'surf',title:'Surf tomorrow morning',context:'Alimanguan · An early start',count:3,image:pictures.surf,category:'experiences',pageTitle:'Alimanguan surf',headline:'Looking for surf buddies?',copy:'3 travelers want to paddle out tomorrow morning. Make a plan together.',cta:'Find Surf Buddies',where:'Alimanguan',when:'Tomorrow · 6:00 AM'},
{id:'transfer',title:'Shared transfer tomorrow',context:'San Vicente · Share the journey',count:6,image:pictures.transport,category:'services',pageTitle:'Along the coast',headline:'Need a ride?',copy:'6 travelers are looking to share a transfer tomorrow. Find your travel companions.',cta:'Share a Ride',where:'San Vicente',when:'Tomorrow · 9:00 AM'},
];
