'use client';
import { useEffect, useMemo, useState } from 'react';
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import { ArrowLeft, ArrowUp, ArrowDown, Upload, Trash2, ShieldCheck, Mail, LogOut, MapPin } from 'lucide-react';
import LocationMapEditor from '@/components/admin/location-map-editor';
import { CONTACT_EMAIL, OWNER_BUCKET, PRO_PRICE, barangays, placeTypes, profileOf, type OwnerAsset, type OwnerPlace, type OwnerProfile, type OwnerRequest } from '@/lib/owner-types';
import './owners.css';

type DirectoryPlace = Pick<OwnerPlace,'id'|'name'|'barangay'|'type'|'display_latitude'|'display_longitude'>;
type Data = { email:string; places:OwnerPlace[]; directory:DirectoryPlace[]; requests:OwnerRequest[]; media:OwnerAsset[] };
type Api = (path:string, body?:unknown, method?:string)=>Promise<any>; // API responses are validated on the server.
const empty:Data = {email:'',places:[],directory:[],requests:[],media:[]};

export default function OwnerPortal({url,apiKey,openMode=false}:{url:string;apiKey:string;openMode?:boolean}) {
  const client=useMemo(()=>url&&apiKey?createClient(url,apiKey):null,[url,apiKey]);
  const [session,setSession]=useState(false),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[email,setEmail]=useState(''),[message,setMessage]=useState(''),[data,setData]=useState<Data>(empty),[placeId,setPlaceId]=useState(''),[query,setQuery]=useState('');
  const api:Api=async(path,body,method='POST')=>{
    const token=(await client?.auth.getSession())?.data.session?.access_token;
    const response=await fetch(path,{method:body===undefined?'GET':method,headers:{Authorization:`Bearer ${token||''}`,...(body===undefined?{}:{'Content-Type':'application/json'})},body:body===undefined?undefined:JSON.stringify(body),cache:'no-store'});
    const result=await response.json();if(!response.ok)throw new Error(result.error||'Request failed.');return result;
  };
  const reload=async()=>{const next=await api('/api/owners');setData(next);};
  const run=async(action:()=>Promise<void>)=>{setBusy(true);setMessage('');try{await action();}catch(e){setMessage(e instanceof Error?e.message:'Unable to complete this request.');}finally{setBusy(false);}};
  useEffect(()=>{
    setPlaceId(new URLSearchParams(location.search).get('place')||'');
    if(openMode){setSession(true);setLoading(false);return;}
    if(!client){setLoading(false);return;}
    const {data:listener}=client.auth.onAuthStateChange((_event,s)=>{setSession(Boolean(s));setLoading(false);});
    return()=>listener.subscription.unsubscribe();
  },[client,openMode]);
  useEffect(()=>{if(session)void run(reload);else setData(empty);},[session]); // Fetch only after Supabase has established the session.
  const select=(id:string)=>{setPlaceId(id);history.replaceState(null,'',`/owners?place=${encodeURIComponent(id)}`);};
  const owned=data.places.find(p=>p.id===placeId);
  const locationInfo=owned||data.directory.find(p=>p.id===placeId);
  const relevant=data.requests.filter(r=>r.place_id===placeId);
  return <main className="owner-shell"><header className="owner-header"><a href="/" aria-label="SANVIC home"><img src="/sanvic-logo.png" alt="SANVIC" width="180" height="24"/></a><a href={placeId?`/#place/${encodeURIComponent(placeId)}`:'/#explore'}><ArrowLeft size={17}/>Back to map</a>{session&&!openMode&&<button onClick={()=>run(async()=>{await client!.auth.signOut();setSession(false);})}><LogOut size={17}/>Sign out</button>}</header>
    <div className="owner-heading"><p className="eyebrow">SANVIC · Business owners</p><h1>{session?(openMode?'Open location editor':'My locations'):'Your place. Your story.'}</h1><p>{openMode?'Temporary build access is open. Choose any location and submit its complete profile, photos and videos for admin review.':'Claim your location and keep its details up to date. Profile management is free.'}</p></div>
    {message&&<p className="owner-message" role="status">{message}</p>}
    {loading?<p role="status">Opening your account…</p>:!client?<section className="owner-panel"><h2>Owner sign-in is being configured.</h2><a href={`mailto:${CONTACT_EMAIL}`}>Contact {CONTACT_EMAIL}</a></section>:!session?<form className="owner-panel owner-login" onSubmit={e=>{e.preventDefault();run(async()=>{const {error}=await client.auth.signInWithOtp({email:email.trim(),options:{emailRedirectTo:`${location.origin}/owners${placeId?`?place=${encodeURIComponent(placeId)}`:''}`}});if(error)throw error;setMessage('Check your email for the secure sign-in link. Open it to return here.');});}}><ShieldCheck/><h2>Sign in to claim or manage</h2><p>Email sign-in identifies your account. Ownership is checked separately by SANVIC.</p><label>Email address<input required type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><button className="owner-primary" disabled={busy}>Email me a sign-in link</button><a href={`mailto:${CONTACT_EMAIL}`}>Need help? Contact us</a></form>:<div className="owner-layout">
      <aside className="owner-panel owner-directory"><h2>Find your location</h2><label>Search by name or barangay<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="BAIA, Port Barton…"/></label><nav aria-label="Your locations">{[...data.places,...data.directory.filter(p=>!data.places.some(o=>o.id===p.id))].filter(p=>`${p.name} ${p.barangay}`.toLowerCase().includes(query.toLowerCase())).map(p=><button key={p.id} className={placeId===p.id?'selected':''} onClick={()=>select(p.id)}><MapPin size={18}/><span><strong>{p.name}</strong><small>{p.barangay} · {data.places.some(o=>o.id===p.id)?'Managed by you':'Claim location'}</small></span></button>)}</nav><a href={`mailto:${CONTACT_EMAIL}?subject=Missing%20SANVIC%20location`}>Location not listed? Contact us</a></aside>
      <div className="owner-content">{!locationInfo?<section className="owner-panel"><h2>Select your location</h2><p>Search the directory to claim or update your place. If it is still an unpublished draft, contact SANVIC.</p></section>:<>
        <section className="owner-panel owner-location-title"><p className="eyebrow">{locationInfo.barangay} · {locationInfo.type}</p><h2>{locationInfo.name}</h2><span>{openMode?'Open for build-phase editing':owned?'Approved manager':'Ownership verification required'}</span></section>
        {owned?<><ProfileEditor key={`${owned.id}-${owned.updated_at}`} place={owned} media={data.media} client={client} api={api} reload={reload} busy={busy} run={run} setMessage={setMessage} pending={relevant.some(r=>r.kind==='changes'&&r.status==='pending')}/><ProPanel key={owned.id} place={owned} media={data.media} client={client} api={api} busy={busy} run={run} reload={reload} setMessage={setMessage} pending={relevant.some(r=>r.kind==='payment'&&r.status==='pending')}/></>:<ClaimForm key={locationInfo.id} place={locationInfo} media={data.media} client={client} api={api} busy={busy} run={run} reload={reload} setMessage={setMessage} pending={relevant.some(r=>r.kind==='claim'&&r.status==='pending')}/>}
        <section className="owner-panel"><h2>Requests & updates</h2>{relevant.length?relevant.map(r=><article className="owner-request" key={r.id}><strong>{r.kind==='changes'?'Profile update':r.kind==='claim'?'Ownership claim':'Pro payment'} · {r.status.replace('_',' ')}</strong><small>{new Date(r.created_at).toLocaleDateString()}</small>{r.review_note&&<p>{r.review_note}</p>}{r.status==='more_info'&&<p>Submit a new request above with the information requested.</p>}</article>):<p>No requests yet.</p>}</section>
      </>}</div>
    </div>}
    <footer className="owner-footer"><a href={`mailto:${CONTACT_EMAIL}`}><Mail size={16}/>{CONTACT_EMAIL}</a><p>SANVIC retains final control of ownership, publishing and paid placements.</p></footer>
  </main>;
}

type Common = {media:OwnerAsset[];client:SupabaseClient;api:Api;reload:()=>Promise<void>;busy:boolean;run:(action:()=>Promise<void>)=>Promise<void>;setMessage:(v:string)=>void;pending:boolean};
function UploadPicker({placeId,purpose,client,api,onUploaded}:{placeId:string;purpose:string;client:SupabaseClient;api:Api;onUploaded:(ids:string[])=>Promise<void>}){
  const [status,setStatus]=useState(''),[busy,setBusy]=useState(false);
  return <div className="owner-upload"><label><Upload size={18}/>{purpose==='gallery'?'Add photos / videos from device':'Attach images or PDF from device'}<input type="file" multiple accept={purpose==='gallery'?'image/jpeg,image/png,image/webp,video/mp4,video/webm,video/quicktime':'image/jpeg,image/png,image/webp,application/pdf'} disabled={busy} onChange={async e=>{
    const files=Array.from(e.target.files||[]);e.target.value='';if(!files.length)return;setBusy(true);const ids:string[]=[];let errorMessage='';
    try{for(let i=0;i<files.length;i++){const file=files[i];setStatus(`Uploading ${i+1} of ${files.length}: ${file.name}`);const ticket=await api('/api/owners/uploads',{placeId,purpose,filename:file.name,contentType:file.type,size:file.size});
      const {error}=await client.storage.from(OWNER_BUCKET).uploadToSignedUrl(ticket.path,ticket.token,file,{contentType:file.type});if(error)throw error;
      await api('/api/owners/uploads',{id:ticket.id},'PATCH');ids.push(ticket.id);}}
    catch(e){errorMessage=e instanceof Error?e.message:'Upload failed. You can retry.';}
    try{if(ids.length)await onUploaded(ids);}catch(e){errorMessage=e instanceof Error?e.message:'Refresh to see completed uploads.';}
    setStatus(errorMessage||`${ids.length} file(s) uploaded.`);setBusy(false);
  }}/></label><small>{purpose==='gallery'?'JPEG, PNG, WebP, MP4, WebM or MOV. Up to 80 MB per file.':'Up to 10 MB per file. Only you and SANVIC admins can see these documents.'}</small><p role="status">{status}</p></div>;
}
function Attachments({ids,media,remove}:{ids:string[];media:OwnerAsset[];remove:(id:string)=>void}){return <div className="owner-attachments">{ids.map(id=>{const a=media.find(x=>x.id===id);return <div key={id}>{a?<a href={a.url} target="_blank" rel="noreferrer">{a.filename}</a>:<span>Attached file</span>}<button type="button" onClick={()=>remove(id)} aria-label="Remove attachment"><Trash2 size={16}/></button></div>;})}</div>;}

function ClaimForm({place,...props}:Common&{place:DirectoryPlace}){
  const [ids,setIds]=useState<string[]>([]),[method,setMethod]=useState('Business contact callback');
  return <form className="owner-panel" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);props.run(async()=>{await props.api('/api/owners',{kind:'claim',placeId:place.id,payload:{name:f.get('name'),phone:f.get('phone'),role:f.get('role'),method,details:f.get('details'),confirmed:f.get('confirmed')==='on'},evidenceIds:ids});await props.reload();props.setMessage('Claim submitted. SANVIC will verify your authority before granting access.');});}}><h2>Claim this location</h2><p>We verify owners and authorized managers using independently confirmed business contact details or ownership evidence.</p><fieldset disabled={props.busy||props.pending}><div className="owner-fields"><label>Your full name<input name="name" required maxLength={180} autoComplete="name"/></label><label>Contact phone<input name="phone" type="tel" required maxLength={80} autoComplete="tel"/></label><label>Your role<select name="role"><option>Owner</option><option>Authorized manager</option></select></label><label>Verification method<select value={method} onChange={e=>setMethod(e.target.value)}><option>Business contact callback</option><option>Business document</option><option>On-site verification</option></select></label></div><label>How can we confirm your authority?<textarea name="details" required minLength={15} maxLength={3000} rows={4} placeholder="Official business website/contact, or details of your supporting document."/></label><p>For a callback, SANVIC uses the business contact it independently verifies—not just the number entered here. For on-site verification, contact us for a temporary challenge code.</p><UploadPicker {...props} placeId={place.id} purpose="evidence" onUploaded={async next=>{setIds(v=>[...v,...next].slice(0,5));await props.reload();}}/><Attachments ids={ids} media={props.media} remove={id=>setIds(ids.filter(x=>x!==id))}/><label className="owner-check"><input required type="checkbox" name="confirmed"/>I own this business or am authorized to manage it. I may share the attached evidence with SANVIC.</label><button className="owner-primary" disabled={props.busy||props.pending}>{props.pending?'Claim awaiting review':'Submit ownership claim'}</button></fieldset></form>;
}

function ProfileEditor({place,...props}:Common&{place:OwnerPlace}){
  const [draft,setDraft]=useState<OwnerProfile>(()=>profileOf(place)),[baseline]=useState(()=>profileOf(place));
  const update=<K extends keyof OwnerProfile>(k:K,v:OwnerProfile[K])=>setDraft(d=>({...d,[k]:v}));
  const reorder=(i:number,delta:number)=>{const ids=[...draft.photo_ids_json];[ids[i],ids[i+delta]]=[ids[i+delta],ids[i]];update('photo_ids_json',ids);};
  return <form className="owner-panel" onSubmit={e=>{e.preventDefault();props.run(async()=>{await props.api('/api/owners',{kind:'changes',placeId:place.id,payload:draft,baseline});await props.reload();props.setMessage('Profile changes submitted. Your current public profile remains visible during review.');});}}><h2>Edit location profile</h2><p>All changes are reviewed before publishing. Removing a photo here removes it from the proposed gallery, not immediately from the live profile.</p><fieldset disabled={props.busy||props.pending}><div className="owner-fields"><label>Business name<input required value={draft.name} onChange={e=>update('name',e.target.value)}/></label><label>Category<select value={draft.type} onChange={e=>update('type',e.target.value as OwnerProfile['type'])}>{placeTypes.map(t=><option key={t}>{t}</option>)}</select></label><label>Barangay<select value={draft.barangay} onChange={e=>update('barangay',e.target.value as OwnerProfile['barangay'])}>{barangays.map(t=><option key={t}>{t}</option>)}</select></label><label>Phone<input type="tel" value={draft.phone} onChange={e=>update('phone',e.target.value)}/></label></div><label>Description<textarea rows={6} maxLength={10000} value={draft.description} onChange={e=>update('description',e.target.value)}/></label><label>Address<input value={draft.address} onChange={e=>update('address',e.target.value)}/></label><div className="owner-fields"><label>Website<input type="url" value={draft.website} onChange={e=>update('website',e.target.value)}/></label><label>Booking / contact URL<input type="url" value={draft.booking_url} onChange={e=>update('booking_url',e.target.value)}/></label><label>Latitude<input required type="number" step="any" min={7.72} max={12.38} value={draft.display_latitude} onChange={e=>update('display_latitude',Number(e.target.value))}/></label><label>Longitude<input required type="number" step="any" min={117.72} max={120.28} value={draft.display_longitude} onChange={e=>update('display_longitude',Number(e.target.value))}/></label></div>
    <LocationMapEditor latitude={draft.display_latitude} longitude={draft.display_longitude} onChange={(lat,lng)=>setDraft(d=>({...d,display_latitude:lat,display_longitude:lng}))}/>
    <div className="owner-fields">{([['hours','Opening hours'],['amenities','Amenities'],['services','Services / tours'],['offers','Menus, rates, packages & events'],['social','Social links']] as const).map(([k,label])=><label key={k}>{label}<textarea rows={3} value={draft.owner_details[k]} onChange={e=>update('owner_details',{...draft.owner_details,[k]:e.target.value})}/></label>)}<label>Operating status<select value={draft.owner_details.closure} onChange={e=>update('owner_details',{...draft.owner_details,closure:e.target.value as OwnerProfile['owner_details']['closure']})}><option value="open">Open</option><option value="temporarily_closed">Temporarily closed</option><option value="permanently_closed">Permanently closed</option></select></label></div>
    <h3>Photos & videos</h3><UploadPicker {...props} placeId={place.id} purpose="gallery" onUploaded={async ids=>{update('photo_ids_json',[...draft.photo_ids_json,...ids]);await props.reload();}}/>
    <div className="owner-gallery">{draft.photo_ids_json.map((id,i)=>{const a=props.media.find(m=>m.id===id);const src=a?.url||`/api/media/${id}`;return <figure key={id}>{a?.content_type.startsWith('video/')?<video src={src} controls playsInline preload="metadata"/>:<img src={src} alt={a?.alt_text||a?.filename||'Location photo'} loading="lazy"/>}<figcaption>{a?.filename||'Existing media'}</figcaption><div><button type="button" disabled={i===0} onClick={()=>reorder(i,-1)} aria-label="Move earlier"><ArrowUp size={16}/></button><button type="button" disabled={i===draft.photo_ids_json.length-1} onClick={()=>reorder(i,1)} aria-label="Move later"><ArrowDown size={16}/></button><button type="button" onClick={()=>setDraft(d=>({...d,photo_ids_json:d.photo_ids_json.filter(x=>x!==id),cover_media_id:d.cover_media_id===id?'':d.cover_media_id}))} aria-label="Remove from gallery"><Trash2 size={16}/></button>{!a?.content_type.startsWith('video/')&&<button type="button" onClick={()=>update('cover_media_id',id)}>{draft.cover_media_id===id?'Cover photo':'Set cover'}</button>}</div></figure>;})}</div>
    {props.media.filter(a=>a.place_id===place.id&&a.purpose==='gallery'&&!draft.photo_ids_json.includes(a.id)).length>0&&<details><summary>Available uploads</summary>{props.media.filter(a=>a.place_id===place.id&&a.purpose==='gallery'&&!draft.photo_ids_json.includes(a.id)).map(a=><div className="owner-request" key={a.id}><span>{a.filename}</span><button type="button" onClick={()=>update('photo_ids_json',[...draft.photo_ids_json,a.id])}>Add to gallery</button>{!a.published&&<button type="button" onClick={()=>{if(confirm('Remove this unused upload from your library?'))props.run(async()=>{await props.api('/api/owners/uploads',{id:a.id},'DELETE');await props.reload();});}}>Delete upload</button>}</div>)}</details>}
    <button className="owner-primary" disabled={props.busy||props.pending}>{props.pending?'Changes awaiting approval':'Submit profile for review'}</button></fieldset></form>;
}

function ProPanel({place,...props}:Common&{place:OwnerPlace}){
  const [ids,setIds]=useState<string[]>([]); const active=place.pro_until&&new Date(place.pro_until)>new Date();
  return <section id="pro" className="owner-panel owner-pro"><p className="eyebrow">Founding member rate</p><h2>SANVIC Pro</h2><p className="owner-price">₱{PRO_PRICE}<span>/ month per location</span></p><p>Featured placement in SANVIC’s location directory and a featured marker on Explore. Profile claiming and management stay free.</p>{active&&<p className="owner-message">Pro active until {new Date(place.pro_until!).toLocaleDateString()}.</p>}<p>Introductory rate. One month per confirmed payment; renew manually. No automatic debit and no promise of lifetime pricing.</p><div className="owner-payment-grid"><div><img className="owner-qr" src="/gcash-sanvic-pro.jpeg" alt="SANVIC GCash payment QR supplied by the team"/><a className="owner-secondary" href="/gcash-sanvic-pro.jpeg" download="SANVIC-GCash.jpeg">Save QR to device</a><p>On your phone, save this QR and choose it from your gallery in GCash. Confirm the recipient with SANVIC if it is unfamiliar before paying.</p></div><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);props.run(async()=>{await props.api('/api/owners',{kind:'payment',placeId:place.id,payload:{method:'GCash',reference:f.get('reference'),note:f.get('note')},evidenceIds:ids});await props.reload();props.setMessage('Payment submitted for verification. Pro activates only after SANVIC confirms receipt.');});}}><fieldset disabled={props.busy||props.pending}><label>GCash transaction reference<input name="reference" required minLength={6} maxLength={80} placeholder="Reference from your receipt"/></label><label>Payment note<textarea name="note" maxLength={2000} rows={3}/></label><UploadPicker {...props} placeId={place.id} purpose="receipt" onUploaded={async next=>{setIds(v=>[...v,...next].slice(0,5));await props.reload();}}/><Attachments ids={ids} media={props.media} remove={id=>setIds(ids.filter(x=>x!==id))}/><button className="owner-primary" disabled={props.busy||props.pending||!ids.length}>{props.pending?'Payment awaiting confirmation':'Submit payment for verification'}</button></fieldset><p>Prefer to arrange payment directly?</p><a href={`mailto:${CONTACT_EMAIL}?subject=${encodeURIComponent(`SANVIC Pro — ${place.name}`)}&body=${encodeURIComponent(`I would like the ₱300/month Founding Member plan for ${place.name} (${place.id}). My owner account: `)}`}>Email {CONTACT_EMAIL}</a></form></div></section>;
}
