'use client';
import { useEffect, useState } from 'react';
import { type OwnerAsset, type OwnerRequest, editableFields, PRO_PRICE } from '@/lib/owner-types';
type Manager={place_id:string;user_id:string;active:boolean;places:{name:string;barangay:string}};
type Data={requests:OwnerRequest[];managers:Manager[];media:OwnerAsset[];pro:{id:string;name:string;pro_until:string}[]};
async function api(body?:unknown,method='POST'){
  const r=await fetch('/api/admin/owners',{method:body===undefined?'GET':method,headers:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),cache:'no-store'});
  const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to load requests.');return d;
}
export default function OwnersPanel(){
  const [data,setData]=useState<Data>({requests:[],managers:[],media:[],pro:[]}),[query,setQuery]=useState(''),[status,setStatus]=useState('pending'),[kind,setKind]=useState('all'),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState<OwnerRequest|null>(null);
  const load=async()=>setData(await api());
  const run=async(action:()=>Promise<void>)=>{setBusy(true);try{await action();}catch(e){setMessage(e instanceof Error?e.message:'Unable to complete review.');}finally{setBusy(false);}};
  useEffect(()=>{void run(load);},[]);
  const change=async(body:unknown)=>run(async()=>{await api(body,'PATCH');await load();setMessage('Updated.');});
  const rows=data.requests.filter(r=>(status==='all'||r.status===status)&&(kind==='all'||r.kind===kind)&&`${r.places?.name} ${r.places?.barangay} ${r.email} ${r.payload.name||''} ${r.payload.phone||''}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="admin-page"><section className="admin-panel"><div className="admin-panel-head"><div><p className="admin-kicker">Owners & Pro</p><h2>Claims, profile changes and payments</h2></div><button disabled={busy} onClick={()=>run(load)}>Refresh</button></div><p>Verify ownership independently. Confirm money in your GCash account before approving a payment. Approved profile changes do not publish a draft location.</p><div className="admin-form-grid"><label className="admin-field">Search<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Location, owner, email, phone, barangay" type="search"/></label><label className="admin-field">Status<select value={status} onChange={e=>setStatus(e.target.value)}>{['pending','approved','rejected','more_info','all'].map(s=><option key={s} value={s}>{s.replace('_',' ')}</option>)}</select></label><label className="admin-field">Request type<select value={kind} onChange={e=>setKind(e.target.value)}>{['all','claim','changes','payment'].map(s=><option key={s}>{s}</option>)}</select></label></div>{message&&<p role="status">{message}</p>}<div className="admin-table-wrap"><table><thead><tr><th>Location</th><th>Owner</th><th>Request</th><th>Status</th><th>Review</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.places?.name}<small>{r.places?.barangay}</small></td><td>{r.email}</td><td>{r.kind}</td><td>{r.status.replace('_',' ')}</td><td><button onClick={()=>setSelected(r)}>Open review</button></td></tr>)}</tbody></table>{!rows.length&&<p>No requests match these filters.</p>}</div></section>
    {selected&&<Review key={selected.id} request={selected} media={data.media} busy={busy} close={()=>setSelected(null)} submit={async(decision,note,fields)=>run(async()=>{await api({id:selected.id,decision,note,fields});await load();setSelected(null);setMessage('Review saved.');})}/>}
    <section className="admin-panel"><h2>Location managers</h2><div className="admin-table-wrap"><table><thead><tr><th>Location</th><th>Owner</th><th>Access</th><th>Action</th></tr></thead><tbody>{data.managers.filter(m=>`${m.places?.name} ${m.places?.barangay} ${data.requests.find(r=>r.user_id===m.user_id)?.email}`.toLowerCase().includes(query.toLowerCase())).map(m=><tr key={`${m.place_id}-${m.user_id}`}><td>{m.places?.name}</td><td>{data.requests.find(r=>r.user_id===m.user_id)?.email||m.user_id}</td><td>{m.active?'Active':'Revoked'}</td><td>{m.active&&<button disabled={busy} onClick={()=>{if(confirm('Revoke this manager’s access?'))change({action:'revoke',placeId:m.place_id,userId:m.user_id});}}>Revoke access</button>}</td></tr>)}</tbody></table></div><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);change({action:'add_manager',placeId:f.get('placeId'),email:f.get('email')});}}><p>After independently verifying their authority, add another claimant as manager.</p><div className="admin-form-grid"><label className="admin-field">Location<select required name="placeId">{Array.from(new Map(data.requests.map(r=>[r.place_id,r])).values()).map(r=><option key={r.place_id} value={r.place_id}>{r.places?.name}</option>)}</select></label><label className="admin-field">Verified claimant email<input required type="email" name="email"/></label></div><button disabled={busy}>Add / restore manager</button></form></section>
    <section className="admin-panel"><h2>Pro placements · ₱{PRO_PRICE}/month</h2>{data.pro.map(p=><div key={p.id} className="admin-panel-head"><span>{p.name} · {new Date(p.pro_until)>new Date()?'Active until':'Expired'} {new Date(p.pro_until).toLocaleDateString()}</span>{new Date(p.pro_until)>new Date()&&<button disabled={busy} onClick={()=>{if(confirm('End this paid placement now? This does not issue a refund.'))change({action:'stop_pro',placeId:p.id});}}>End placement</button>}</div>)}<DirectPayment managers={data.managers.filter(m=>m.active)} busy={busy} onSubmit={body=>run(async()=>{await api(body);await load();setMessage('Direct payment recorded as pending. Open Payments and confirm it after checking your account.');})}/></section>
  </div>;
}
function DirectPayment({managers,busy,onSubmit}:{managers:Manager[];busy:boolean;onSubmit:(body:unknown)=>void}){return <form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const m=managers[Number(f.get('manager'))];if(!m)return;onSubmit({directPayment:true,placeId:m.place_id,userId:m.user_id,reference:f.get('reference'),note:f.get('note')});}}><h3>Payment arranged by email</h3><p>Record an externally received ₱300 payment for an approved owner, then review and confirm it below the Payments filter.</p><div className="admin-form-grid"><label className="admin-field">Owner/location<select name="manager" required>{managers.map((m,i)=><option key={`${m.place_id}-${m.user_id}`} value={i}>{m.places?.name} · {m.user_id.slice(0,8)}</option>)}</select></label><label className="admin-field">Unique payment reference<input name="reference" required minLength={6} maxLength={80}/></label><label className="admin-field">Payment arrangement notes<textarea name="note" required minLength={3} maxLength={2000}/></label></div><button disabled={busy||!managers.length}>Record for review</button></form>;}
function Review({request:r,media,busy,close,submit}:{request:OwnerRequest;media:OwnerAsset[];busy:boolean;close:()=>void;submit:(d:string,n:string,f:string[])=>void}){
  const changed=editableFields.filter(k=>JSON.stringify(r.payload[k])!==JSON.stringify(r.baseline[k]));
  const [fields,setFields]=useState<string[]>([...changed]),[note,setNote]=useState(''),[checked,setChecked]=useState(false);
  const evidence=media.filter(a=>r.evidence_ids.includes(a.id));
  const galleryIds=new Set([...(Array.isArray(r.payload.photo_ids_json)?r.payload.photo_ids_json as string[]:[]),...(Array.isArray(r.baseline.photo_ids_json)?r.baseline.photo_ids_json as string[]:[])]);
  const show=(value:unknown)=>typeof value==='string'?value:JSON.stringify(value,null,2);
  return <section className="admin-panel" aria-label="Request review"><div className="admin-panel-head"><h2>{r.places?.name} · {r.kind}</h2><button onClick={close}>Close</button></div><p>{r.email}</p>{r.kind==='changes'?<div className="admin-table-wrap"><table><thead><tr><th>Approve</th><th>Field</th><th>Before submission</th><th>Proposed</th></tr></thead><tbody>{changed.map(k=><tr key={k}><td><input type="checkbox" aria-label={`Approve ${k}`} checked={fields.includes(k)} onChange={e=>setFields(v=>e.target.checked?[...v,k]:v.filter(x=>x!==k))}/></td><th>{k.replaceAll('_',' ')}</th><td style={{whiteSpace:'pre-wrap',maxWidth:320}}>{show(r.baseline[k])}</td><td style={{whiteSpace:'pre-wrap',maxWidth:320}}>{show(r.payload[k])}</td></tr>)}</tbody></table><p>The save is blocked if an approved field changed after this request was submitted.</p></div>:<dl>{Object.entries(r.payload).map(([k,v])=><div key={k}><dt>{k}</dt><dd style={{whiteSpace:'pre-wrap'}}>{show(v)}</dd></div>)}</dl>}
    <div className="owner-review-media">{[...evidence,...media.filter(a=>galleryIds.has(a.id))].map(a=><figure key={a.id}>{a.content_type.startsWith('image/')?<img style={{width:180,height:140,objectFit:'contain'}} src={a.url} alt={a.filename}/>:a.content_type.startsWith('video/')?<video style={{width:220}} controls playsInline preload="metadata" src={a.url}/>:null}<figcaption><a href={a.url} target="_blank" rel="noreferrer">{a.filename}</a></figcaption></figure>)}</div>
    {r.status==='pending'?<><label className="admin-field">Review note (visible to owner)<textarea required minLength={3} maxLength={3000} value={note} onChange={e=>setNote(e.target.value)} placeholder="Verification performed, or information still needed"/></label><label className="admin-check"><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)}/>{r.kind==='payment'?'I verified receipt of ₱300 in our account; a screenshot alone is not proof.':r.kind==='claim'?'I independently verified this person’s authority to manage this location.':'I reviewed the selected changes and media for publication.'}</label><div className="admin-panel-head"><button disabled={busy||note.trim().length<3} onClick={()=>submit('more_info',note,[])}>Request more information</button><button disabled={busy||note.trim().length<3} onClick={()=>submit('rejected',note,[])}>Reject</button><button className="admin-primary" disabled={busy||!checked||note.trim().length<3||(r.kind==='changes'&&!fields.length)} onClick={()=>submit('approved',note,fields)}>{r.kind==='payment'?'Confirm payment & activate one month':'Approve'}</button></div></>:<p>{r.status} · {r.review_note}</p>}
  </section>;
}
